export default {
  id: 'moyu',
  name: '摸鱼绿',
  description: '微信绿主色，浅绿点缀，清爽护眼',
  vars: {
    colors: {
      accent: '#07C160',
      accentLight: '#E8F8EF',
      heading: '#1A1A1A',
      text: '#3F3F3F',
      muted: '#9CA3AF',
      highlight: '#FFE58F',
      cardBg: '#F6F8FA',
      border: '#E5E7EB',
      codeBg: '#1E1E1E',
      codeText: '#D4D4D4',
    },
    font: {
      base: '15px',
      title: '22px',
      h2: '17px',
      code: '13px',
      family:
        "-apple-system,BlinkMacSystemFont,'PingFang SC','Hiragino Sans GB','Microsoft YaHei',sans-serif",
      mono: "Menlo,Consolas,'Courier New',monospace",
    },
    radius: { card: '12px', tag: '6px' },
    spacing: { paragraph: '10px', block: '24px' },
    codeTokens: {
      keyword: '#C586C0',
      built_in: '#4EC9B0',
      type: '#4EC9B0',
      literal: '#569CD6',
      number: '#B5CEA8',
      string: '#CE9178',
      regexp: '#D16969',
      symbol: '#569CD6',
      title: '#DCDCAA',
      function: '#DCDCAA',
      attr: '#9CDCFE',
      attribute: '#9CDCFE',
      variable: '#9CDCFE',
      'template-variable': '#9CDCFE',
      comment: '#6A9955',
      doctag: '#6A9955',
      meta: '#608B4E',
      tag: '#569CD6',
      name: '#569CD6',
      section: '#569CD6',
      'selector-tag': '#D7BA7D',
      'selector-class': '#D7BA7D',
      property: '#9CDCFE',
      params: '#9CDCFE',
      operator: '#D4D4D4',
      punctuation: '#D4D4D4',
    },
  },
  components: {},
}
